# Site settings
title: OpenPyViv
header-img: img/home-bg.jpg
email: viviane.pons@lri.fr
description: "A blog about research, math, progamming and whatever I feel like talking about... "
baseurl: ""
url: "http://vivianepons.github.io"
twitter_username: PyViv
github_username:  VivianePons

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
