# Site settings
title: OpenPyViv
header-img: img/home-bg.jpg
header-gradient: "linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6))"
email: viviane.pons@lri.fr
description: "A blog about research, math, progamming and whatever I feel like talking about... "
baseurl: ""
url: "http://openpyviv.com"
twitter_username: PyViv
github_username:  VivianePons
plugins: [jekyll-paginate, jekyll-redirect-from]
disqus_shortname: openpyviv

# Build settings
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

collections:
    tagpages:
        output: true
        permalink: /tag/:path
